name: Build Database
on:
  push:
    paths: ['Pages/**']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: python build_database.py
      - name: Deploy
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add assets/database.js
          git commit -m "Update db" || exit 0
          git push